import { createSlice } from "@reduxjs/toolkit";

const initialState = {
    items: [
        {
            id: 1,
            title: "How  Engineers Can Build PERMANENT Job Security in 2025",
            description: "Description for Video 1",
            thumbnail: "https://i.ytimg.com/vi/Ndz3PYADcvA/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDGEGJ_dxEQj8jz68y0-wb_GVNg4g",
            url: "https://www.youtube.com/watch?v=Ndz3PYADcvA",
            profile: "https://yt3.ggpht.com/0wMhEQe-e_FLwpQgUjDa82CbWVH6IplMb2Z8-JC_ysJ4aIy0d4cLzdd2omFnxEzPoe31ICio=s68-c-k-c0x00ffffff-no-rj",
            channel: "Channel 1",
            views: 1000,
            likes: 100,
            duration: "10:00",
            publishedAt: "2025-05-10",
        },
        {
            id: 2,
            title: "Ka Kong Bertina Kam Donkam Khuslai Ban Ïoh Pyndep PhD | Mang U CM 1.35 Lak Na CMSG",
            description: "Description for Video 2",
            thumbnail: "https://i.ytimg.com/vi/bGnRoVFwUeE/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCF2Kp2YFNuCp2eRdpMRUs1pbTAag",
            url: "https://www.youtube.com/watch?v=bGnRoVFwUeE",
            profile: "https://yt3.ggpht.com/uzqjVPREImGM9v8N63I6sgpByD7WfVTBR6e4UKPrhEXLXGBB9dzOWHeLd30Ip2o4JQ96P22Tp2o=s68-c-k-c0x00ffffff-no-rj",
            channel: "Channel 2",
            views: 24000000,
            likes: 200,
            duration: "20:00",
            publishedAt: "2023-02-01",
        },
        {
            id: 3,
            title: "200W Camping Power Station 192Wh Power Bank 60000mAh LiFePo4",
            description: "Description for Video 3",
            thumbnail: "https://i.ytimg.com/vi/X3yATXAWL_g/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBDEpQpfSZda3ysTuYJYdatZ1wcRQ",
            url: "https://www.youtube.com/watch?v=X3yATXAWL_g",
            profile: "https://yt3.ggpht.com/0CuJkUiY3A3XobJeYDDSeZInfMUyW2o01cw5PZn1gRN9y33D_pFW_i0CysAbaNMPv28a0FQ2=s68-c-k-c0x00ffffff-no-rj",
            channel: "Channel 3",
            views: 3000,
            likes: 300,
            duration: "30:00",
            publishedAt: "2023-03-01",
        },
        {
            id: 4,
            title: "The Beginner's Guide to Clean Architecture",
            description: "Description for Video 4",
            thumbnail: "https://i.ytimg.com/vi/TQdLgzVk2T8/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLC383Mm6ytkTCIhNNt3yPRn-sVWIg",
            url: "https://www.youtube.com/watch?v=TQdLgzVk2T8",
            profile: "https://yt3.ggpht.com/E_K5727J3QuOP20WbsepnNRkiyb8CFdj2xu_WCA7NL717A356D2VpPGjH_n6BXPtumyKuEFvjA=s68-c-k-c0x00ffffff-no-rj",
            channel: "Channel 4",
            views: 4000,
            likes: 400,
            duration: "40:00",
            publishedAt: "2023-04-01",
        },
        {
            id: 5,
            title: "𝙿𝚊𝚠𝚗𝚊𝚖 𝚔𝚒 𝚔𝚑𝚢𝚗𝚗𝚊𝚑 𝚋𝚊 𝚛𝚠𝚊𝚒 𝚁𝚒 𝚕𝚞𝚖 𝚋𝚊𝚍 𝚟𝚊𝚗𝚍𝚎 𝚖𝚊𝚝𝚊𝚛𝚊𝚖  𝙷𝚊 𝚔𝚢𝚕𝚕𝚎𝚗𝚐 𝚔𝚊 𝚙𝚢𝚛𝚝𝚑𝚎𝚒",
            description: "Description for Video 5",
            thumbnail: "https://i.ytimg.com/vi/rl5mkbx9yNU/hq720.jpg?sqp=-oaymwFBCNAFEJQDSFryq4qpAzMIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB8AEB-AH-CYAC0AWKAgwIABABGEEgZSg4MA8=&rs=AOn4CLAdVMWBOMocZWoKyrNq0Y2d-v0WBw",
            url: "https://www.youtube.com/watch?v=rl5mkbx9yNU",
            profile: "https://yt3.ggpht.com/ZP7yv6nmEtYFpdry-04aUdz72-jQWH8wwkfXpQKNUEKVp4Dml6wV380Sb4N96XYNVvl1vwEMSQ=s68-c-k-c0x00ffffff-no-rj",
            channel: "Channel 5",
            views: 5000,
            likes: 500,
            duration: "50:00",
            publishedAt: "2023-05-01",
        },
        {
            id: 6,
            title: "Career Podcast || E1 - Content Creator || Code Freemen",
            description: "Description for Video 6",
            thumbnail: "https://i.ytimg.com/vi/TWM-atA8ft8/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBlWXgi3v86mpOgZtOSUyzVeRI20Q",
            url: "https://www.youtube.com/watch?v=TWM-atA8ft8",
            profile: "https://yt3.ggpht.com/kd_wAtpKhygpsXyZHGE5zDz2nM6dZmavS5WtCRHxy6VSZTAQY0UumPRSoZuj6EuYWaYnQ05C=s68-c-k-c0x00ffffff-no-rj",
            channel: "Channel 6",
            views: 6000,
            likes: 600,
            duration: "60:00",
            publishedAt: "2023-06-01",
        },
        {
            id: 7,
            title: "How  Engineers Can Build PERMANENT Job Security in 2025",
            description: "Description for Video 7",
            thumbnail: "https://i.ytimg.com/vi/Ndz3PYADcvA/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDGEGJ_dxEQj8jz68y0-wb_GVNg4g",
            url: "https://www.youtube.com/watch?v=Ndz3PYADcvA",
            profile: "https://yt3.ggpht.com/0wMhEQe-e_FLwpQgUjDa82CbWVH6IplMb2Z8-JC_ysJ4aIy0d4cLzdd2omFnxEzPoe31ICio=s68-c-k-c0x00ffffff-no-rj",
            channel: "Channel 7",
            views: 7000,
            likes: 700,
            duration: "70:00",
            publishedAt: "2023-07-01",
        },
        {
            id: 8,
            title: "Ka Kong Bertina Kam Donkam Khuslai Ban Ïoh Pyndep PhD | Mang U CM 1.35 Lak Na CMSG",
            description: "Description for Video 8",
            thumbnail: "https://i.ytimg.com/vi/bGnRoVFwUeE/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCF2Kp2YFNuCp2eRdpMRUs1pbTAag",
            url: "https://www.youtube.com/watch?v=bGnRoVFwUeE",
            profile: "https://yt3.ggpht.com/uzqjVPREImGM9v8N63I6sgpByD7WfVTBR6e4UKPrhEXLXGBB9dzOWHeLd30Ip2o4JQ96P22Tp2o=s68-c-k-c0x00ffffff-no-rj",
            channel: "Channel 8",
            views: 8000,
            likes: 800,
            duration: "80:00",
            publishedAt: "2023-08-01",
        },
        {
            id: 9,
            title: "200W Camping Power Station 192Wh Power Bank 60000mAh LiFePo4",
            description: "Description for Video 9",
            thumbnail: "https://i.ytimg.com/vi/X3yATXAWL_g/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBDEpQpfSZda3ysTuYJYdatZ1wcRQ",
            url: "https://www.youtube.com/watch?v=X3yATXAWL_g",
            profile: "https://yt3.ggpht.com/0CuJkUiY3A3XobJeYDDSeZInfMUyW2o01cw5PZn1gRN9y33D_pFW_i0CysAbaNMPv28a0FQ2=s68-c-k-c0x00ffffff-no-rj",
            channel: "Channel 9",
            views: 9000,
            likes: 900,
            duration: "90:00",
            publishedAt: "2023-09-01",            
        },
        {
            id: 10,
            title: "The Beginner's Guide to Clean Architecture",
            description: "Description for Video 10",
            thumbnail: "https://i.ytimg.com/vi/TQdLgzVk2T8/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLC383Mm6ytkTCIhNNt3yPRn-sVWIg",
            url: "https://www.youtube.com/watch?v=TQdLgzVk2T8",
            profile: "https://yt3.ggpht.com/E_K5727J3QuOP20WbsepnNRkiyb8CFdj2xu_WCA7NL717A356D2VpPGjH_n6BXPtumyKuEFvjA=s68-c-k-c0x00ffffff-no-rj",
            channel: "Channel 10",
            views: 10000,
            likes: 1000,
            duration: "100:00",
            publishedAt: "2023-10-01",
        },
        {
            id: 11,
            title: "𝙿𝚊𝚠𝚗𝚊𝚖 𝚔𝚒 𝚔𝚑𝚢𝚗𝚗𝚊𝚑 𝚋𝚊 𝚛𝚠𝚊𝚒 𝚁𝚒 𝚕𝚞𝚖 𝚋𝚊𝚍 𝚟𝚊𝚗𝚍𝚎 𝚖𝚊𝚝𝚊𝚛𝚊𝚖  𝙷𝚊 𝚔𝚢𝚕𝚕𝚎𝚗𝚐 𝚔𝚊 𝚙𝚢𝚛𝚝𝚑𝚎𝚒",
            description: "Description for Video 11",
            thumbnail: "https://i.ytimg.com/vi/rl5mkbx9yNU/hq720.jpg?sqp=-oaymwFBCNAFEJQDSFryq4qpAzMIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB8AEB-AH-CYAC0AWKAgwIABABGEEgZSg4MA8=&rs=AOn4CLAdVMWBOMocZWoKyrNq0Y2d-v0WBw",
            url: "https://www.youtube.com/watch?v=rl5mkbx9yNU",
            profile: "https://yt3.ggpht.com/ZP7yv6nmEtYFpdry-04aUdz72-jQWH8wwkfXpQKNUEKVp4Dml6wV380Sb4N96XYNVvl1vwEMSQ=s68-c-k-c0x00ffffff-no-rj",
            channel: "Channel 11",
            views: 11000,
            likes: 1100,
            duration: "110:00",
            publishedAt: "2023-11-01",
        },
        {
            id: 12,
            title: "Career Podcast || E1 - Content Creator || Code Freemen",
            description: "Description for Video 12",
            thumbnail: "https://i.ytimg.com/vi/TWM-atA8ft8/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLBlWXgi3v86mpOgZtOSUyzVeRI20Q",
            url: "https://www.youtube.com/watch?v=TWM-atA8ft8",
            profile: "https://yt3.ggpht.com/kd_wAtpKhygpsXyZHGE5zDz2nM6dZmavS5WtCRHxy6VSZTAQY0UumPRSoZuj6EuYWaYnQ05C=s68-c-k-c0x00ffffff-no-rj",
            channel: "Channel 12",
            views: 12000,
            likes: 1200,
            duration: "120:00",
            publishedAt: "2023-12-01",
        },
        {
            id: 13,
            title: "How Engineers Can Build PERMANENT Job Security in 2025",
            description: "Description for Video 13",
            thumbnail: "https://i.ytimg.com/vi/Ndz3PYADcvA/hq720.jpg?sqp=-oaymwEnCNAFEJQDSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLDGEGJ_dxEQj8jz68y0-wb_GVNg4g",
            url: "https://www.youtube.com/watch?v=Ndz3PYADcvA",
            profile: "https://yt3.ggpht.com/0wMhEQe-e_FLwpQgUjDa82CbWVH6IplMb2Z8-JC_ysJ4aIy0d4cLzdd2omFnxEzPoe31ICio=s68-c-k-c0x00ffffff-no-rj",
            channel: "Channel 13",
            views: 13000,
            likes: 1300,
            duration: "130:00",
            publishedAt: "2023-01-02",
        }
    ],
}

const videoSlice = createSlice({
    name: "video",
    initialState,
})

export default videoSlice.reducer;